# -*- coding: utf-8 -*-
"""Primitive_Data_Type_and_Strings_in_Python.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1rWPIn_mdDcBNbD7n5Z3__gWKJkPTByEz
"""

#Primitive_Type

#1_Intetger
#2_Floating
#3_Boolean

#String

#1_String
#2_Slicing_&_Indexing
#3_String_class_methods

#Primary_Data_types_in_Python:

#1_Strings (use for text analysis)
#2_Integers
#3_Floating
#4_Boolean

name = "Suneel Shivani"
age = 21
age2= 21.0
yonger = True

print(type(name))
print(type(age))
print(type(age2))
print(type(yonger))

#_Integer

#

age = 5
print(age)

#_Floating/in_Decimal

price = 100.0
print(price)

#_Boolean

brith_year = 1947
age = 2024 - brith_year
criteria = 18
elgibilty = age >= criteria
print("you elgilbilty to vote is?", elgibilty)

# Assignment 1

applicant_income = 50000
price_of_house = 100000
discount = 10/100 #True

elgibilty = applicant_income >= 50000
print("You elgibilable for discount is :", discount)

#_Strings

#_Print_Strings_as_output_on_screen

print("Hello World")
print("Suneel Shivani")
print("Hello Students. ")
print("Hey, Good Morning Dear.")
print("My name is Suneel.")
print("My age is 21.")
print("My name is Suneel,", "My age is 21.")
print("23")

#_String_Slicing

#

str = email = "username@domain.com"
print(str[0:8])
print(str[:4]) #_print(str[0:4])
print(str[9:]) #_print(str[9:len(str)])

#

str = name ='Aleem'
print(str[0:5]) #RangeFind

#_String_Indexing

str = name = "Suneel Shivani"

print(str[0])
print(str[8])
print(str[9])

#_String_class_methods_OR_#_Strings_functions

#_

str = name = "Suneel Shivani"

print(name.upper())
print(name.lower())
print(name.find('h'))

print(name.replace("Shivani", "Sharma" ))
print("i" in name)
print(name.index('e'))
print(name.count('i'))

print(len(str)) #_Find_the_Lenght_of_words.

#_

email = 'xyz@domain.com'
domain_name = email.split("@")
print(domain_name)